---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SharkSync.Web.Api Stack
Resources:
  SharkSyncWebApiServerlessProxy:
    Type: AWS::Serverless::Function
    Properties:
      Handler: SharkSync.Web.Api::SharkSync.Web.Api.LambdaEntryPoint::FunctionHandlerAsync
      Runtime: dotnetcore2.0
      CodeUri: ''
      MemorySize: 256
      Timeout: 30
      Role: 
      Policies:
      - AWSLambdaFullAccess
      Events:
        ApiProxy:
          Type: Api
          Properties:
            Path: "/{proxy+}"
            Method: ANY
