version: 0.2

phases:
  build:
    commands:
      - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      - apt-get install -y nodejs
      - dotnet restore
      - dotnet build --configuration release
      - dotnet publish --configuration release
      - cd SharkSync.Web.Api
      - dotnet lambda package --configuration release
      - aws s3 cp bin/release/netcoreapp2.0/SharkSync.Web.Api.zip s3://io.sharksync.builds/SharkSync.Web.Api.zip
      - cd ../SharkSync.Web
      - aws s3 cp bin/Release/netcoreapp2.0/publish/wwwroot s3://io.sharksync.web/ --recursive
      - aws cloudformation deploy --template-file ../cloudformation.yaml --stack-name sharksync-web --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset
      - aws cloudfront create-invalidation --distribution-id E2GJ1WJW08B0G1 --paths /index.html