version: 0.2

phases:
  build:
    commands:
      - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      - apt-get install -y nodejs
      - npm install
      - dotnet restore
      - dotnet build --configuration release
      - dotnet publish --configuration release
      - cd SharkSync.Web.Api
      - dotnet lambda package --configuration release --framework netcoreapp2.0
      - cd ../
      - bash create-github-release.sh github_api_token=${GITHUB_TOKEN} owner=sharksync repo=sharktank
      - echo "Next version: ${BUILD_VERSION}"
      - npm run-script grunt postBuild
      - zip -r SharkSync.Web.Html.zip SharkSync.Web/bin/Release/netcoreapp2.0/publish/wwwroot
      - bash upload-binary.sh github_api_token=${GITHUB_TOKEN} owner=sharksync repo=sharktank tag=LATEST filename=./SharkSync.Web.Api/bin/release/netcoreapp2.0/SharkSync.Web.Api.zip
      - bash upload-binary.sh github_api_token=${GITHUB_TOKEN} owner=sharksync repo=sharktank tag=LATEST filename=./SharkSync.Web.Html.zip
      - bash upload-binary.sh github_api_token=${GITHUB_TOKEN} owner=sharksync repo=sharktank tag=LATEST filename=./cloudformation.yaml