version: 0.2

phases:
  build:
    commands:
      - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      - apt-get install -y nodejs
      - npm install
      - dotnet restore
      - dotnet build --configuration release
      - dotnet publish --configuration release
      - cd SharkSync.Web.Api
      - dotnet lambda package --configuration release
      - cd ../
      - curl --data '{"tag_name":"v1.0.0","target_commitish":"master","name":"v1.0.0","body":"Release of version 1.0.0","draft":false,"prerelease":false}' https://api.github.com/repos/sharksync/sharktank/releases?access_token=${GITHUB_TOKEN}
      - bash upload-github-release-asset.sh github_api_token=${GITHUB_TOKEN} owner=sharksync repo=sharktank tag=v1.0.0 filename=./SharkSync.Web.Api/bin/release/netcoreapp2.0/SharkSync.Web.Api.zip
      - npm run-script grunt postBuild
      - LAMBDAZIP=$(ls SharkSync.Web.Api/bin/release/netcoreapp2.0 | grep ".zip$" | head -1)
      - aws s3 cp SharkSync.Web.Api/bin/release/netcoreapp2.0/$LAMBDAZIP s3://io.sharksync.builds/$LAMBDAZIP
      - aws s3 cp SharkSync.Web/bin/Release/netcoreapp2.0/publish/wwwroot s3://io.sharksync.web/ --recursive
      - aws cloudformation deploy --template-file cloudformation.yaml --stack-name sharksync-web --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset --parameter-overrides LambdaZip=$LAMBDAZIP
      - aws cloudfront create-invalidation --distribution-id E2GJ1WJW08B0G1 --paths "/" "/Console/*"