---
AWSTemplateFormatVersion: '2010-09-09'
Description: SharkSync.Web Stack
Resources:
  S3BucketWeb:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: io.sharksync.web
  S3BucketPolicyBucketWebCloudfront:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: S3BucketWeb
      PolicyDocument:
        Statement:
        - Action:
          - s3:GetObject
          Effect: Allow
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - Ref: S3BucketWeb
              - "/*"
          Principal:
            AWS:
              - 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity E2L91VF2FR5I1N'
  LambdaEdgeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
            - edgelambda.amazonaws.com
          Action:
          - sts:AssumeRole
      RoleName: 'lambda-edge-role'
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  CloudFrontWebApp:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: io.sharksync.web.s3.amazonaws.com
          Id: s3
          S3OriginConfig:
            OriginAccessIdentity: origin-access-identity/cloudfront/E2L91VF2FR5I1N
        Enabled: 'true'
        Comment: io.sharksync.web
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          TargetOriginId: s3
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
          SmoothStreaming: 'false'
          Compress: 'true'
          ViewerProtocolPolicy: redirect-to-https
          LambdaFunctionAssociations:
            - EventType: origin-request
              LambdaFunctionARN: arn:aws:lambda:us-east-1:429810410321:function:sharksync-web-origin-request:1
        PriceClass: PriceClass_All
        HttpVersion: http2
  AccountTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Account
      AttributeDefinitions:
      - AttributeName: Id
        AttributeType: S
      KeySchema:
      - AttributeName: Id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  ApplicationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Application
      AttributeDefinitions:
      - AttributeName: Id
        AttributeType: S
      KeySchema:
      - AttributeName: Id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  DeviceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Device
      AttributeDefinitions:
      - AttributeName: ApplicationId
        AttributeType: S
      - AttributeName: Id
        AttributeType: S
      KeySchema:
      - AttributeName: ApplicationId
        KeyType: HASH
      - AttributeName: Id
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1