---
AWSTemplateFormatVersion: '2010-09-09'
Description: SharkSync Stack

Parameters:
  WebsiteDomain: 
    Type: String
    Default: www.example.com
    Description: The DNS name of an existing Amazon Route 53 hosted zone domain name e.g. www.example.com
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: must be a valid DNS zone name.
  WebsiteCertificateArn:
    Type: String
    Description: the ARN of an ACM certificate for the website domain that must be in the us-east-1 region.
    AllowedPattern: "arn:aws:acm:.*"
  ApiDomain: 
    Type: String
    Default: api.example.com
    Description: The DNS name of an existing Amazon Route 53 hosted zone domain name e.g. api.example.com
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: must be a valid DNS zone name.
  ApiCertificateArn:
    Type: String
    Description: the ARN of an ACM certificate for the API domain that must be in the us-east-1 region.
    AllowedPattern: "arn:aws:acm:.*"

Resources:

  S3BucketWeb:
    Type: AWS::S3::Bucket

  CloudFrontAccessIdentity:
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref 'AWS::StackName'

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: S3BucketWeb
      PolicyDocument:
        Statement:
        - Action:
          - s3:GetObject
          Effect: Allow
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - Ref: S3BucketWeb
              - "/*"
          Principal:
            AWS:
              - Fn::Join:
                - ''
                - - 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity '
                  - Ref: CloudFrontAccessIdentity

  LambdaEdgeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
            - edgelambda.amazonaws.com
          Action:
          - sts:AssumeRole
      RoleName: 'lambda-edge-role'
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  CloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        IPV6Enabled: true
        HttpVersion: http2
        Comment: !Ref 'AWS::StackName'
        Aliases: [!Ref WebsiteDomain]
        ViewerCertificate:
          AcmCertificateArn: !Ref WebsiteCertificateArn
          SslSupportMethod: sni-only
        Origins:
        - Id: s3
          DomainName: !GetAtt S3BucketWeb.DomainName
          S3OriginConfig:
            OriginAccessIdentity: 
              Fn::Join:
               - ''
               - - 'origin-access-identity/cloudfront/'
                 - Ref: CloudFrontAccessIdentity
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          TargetOriginId: s3
          MinTTL: 3153600000
          DefaultTTL: 3153600000
          MaxTTL: 3153600000
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          SmoothStreaming: false
          Compress: true
          ViewerProtocolPolicy: redirect-to-https
          LambdaFunctionAssociations:
            - EventType: origin-request
              LambdaFunctionARN: 
                Fn::GetAtt:
                  - LambdaEdgeOriginRequest
                  - LambdaVersionedArn
        PriceClass: PriceClass_All

  DNSARecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: 
        Fn::Join:
         - ''
         - - !Ref WebsiteDomain
           - '.'
      Type: A
      HostedZoneName: 
        Fn::Join:
         - ''
         - - !Select [1, !Split [".", !Ref WebsiteDomain]]
           - '.'
           - !Select [2, !Split [".", !Ref WebsiteDomain]]
           - '.'
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt CloudFront.DomainName
  DNSAAAARecord:    
    Type: AWS::Route53::RecordSet
    Properties:
      Name: 
        Fn::Join:
         - ''
         - - !Ref WebsiteDomain
           - '.'
      Type: AAAA
      HostedZoneName: 
        Fn::Join:
         - ''
         - - !Select [1, !Split [".", !Ref WebsiteDomain]]
           - '.'
           - !Select [2, !Split [".", !Ref WebsiteDomain]]
           - '.'
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt CloudFront.DomainName

  AccountTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Account
      AttributeDefinitions:
      - AttributeName: Id
        AttributeType: S
      KeySchema:
      - AttributeName: Id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  ApplicationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Application
      AttributeDefinitions:
      - AttributeName: Id
        AttributeType: S
      KeySchema:
      - AttributeName: Id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  DeviceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Device
      AttributeDefinitions:
      - AttributeName: ApplicationId
        AttributeType: S
      - AttributeName: Id
        AttributeType: S
      KeySchema:
      - AttributeName: ApplicationId
        KeyType: HASH
      - AttributeName: Id
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  WebApiLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      RoleName: 'web-api-lambda-role'
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  WebApiLambdaRoleInlinePolicy:
    Type: AWS::IAM::Policy
    Properties: 
      PolicyName: "web-api-policy"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: Allow
            Resource: ["*"]
            Action: ["secretsmanager:*", "dynamodb:*"]
      Roles: 
        - Ref: "WebApiLambdaRole"

  WebApiLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: SharkSync.Web.Api::SharkSync.Web.Api.LambdaEntryPoint::FunctionHandlerAsync
      Code:
        S3Bucket: io.sharksync.builds
        S3Key: 
          Fn::Join:
          - ''
          - - 'v0.0.0'
            - '/SharkSync.Web.Api.zip'
      Role:
        Fn::GetAtt:
          - WebApiLambdaRole
          - Arn
      Runtime: dotnetcore2.0
      MemorySize: 256
      Timeout: 300

  WebApiGatewayApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: SharkSync.WebApi

  WebApiDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      CertificateArn: !Ref ApiCertificateArn
      DomainName: !Ref ApiDomain

  WebApiMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref WebApiDomainName
      RestApiId: !Ref WebApiGatewayApi
      Stage: Prod

  ApiCNAMERecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: 
        Fn::Join:
         - ''
         - - !Ref ApiDomain
           - '.'
      Type: CNAME
      TTL: '900'
      ResourceRecords:
        - !GetAtt WebApiDomainName.DistributionDomainName
      HostedZoneName: 
        Fn::Join:
          - ''
          - - !Select [1, !Split [".", !Ref ApiDomain]]
            - '.'
            - !Select [2, !Split [".", !Ref ApiDomain]]
            - '.'

  WebApiGatewayResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt WebApiGatewayApi.RootResourceId
      RestApiId: !Ref WebApiGatewayApi
      PathPart: '{proxy+}'

  WebApiGatewayProxyMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      ResourceId: !Ref WebApiGatewayResource
      RestApiId: !Ref WebApiGatewayApi
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: ANY
        Type: AWS_PROXY
        Uri: !Sub
        - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Arn}/invocations
        - Arn:
            Fn::GetAtt:
            - WebApiLambda
            - Arn
        PassthroughBehavior: WHEN_NO_MATCH
        IntegrationResponses:
          - StatusCode: 200

  WebApiGatewayDeployment:
    DependsOn:
      - WebApiGatewayProxyMethod
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      RestApiId: !Ref WebApiGatewayApi
      StageName: Prod

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt 
        - WebApiLambda
        - Arn
      Action: 'lambda:InvokeFunction'
      Principal: apigateway.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn:
        Fn::Join:
        - ''
        - - 'arn:aws:execute-api:'
          - Ref: AWS::Region
          - ":"
          - Ref: AWS::AccountId
          - ":"
          - Ref: WebApiGatewayApi
          - "/*/*/*"

  DeploymentLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      RoleName: 'deployment-lambda-role'
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  DeploymentLambdaRoleInlinePolicy:
    Type: AWS::IAM::Policy
    Properties: 
      PolicyName: "deployment-policy"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: Allow
            Resource: 
              Fn::Join:
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3BucketWeb
                - '/*'
            Action: ["s3:PutObject", "s3:GetObject"]
          - Effect: Allow
            Resource: 
              Fn::Join:
              - ''
              - - 'arn:aws:lambda:*:*:function:'
                - !Ref 'AWS::StackName'
                - '-*'
            Action: ["lambda:CreateFunction", "lambda:UpdateFunctionCode", "lambda:DeleteFunction"]
          - Effect: Allow
            Resource: 
              Fn::GetAtt:
                - LambdaEdgeRole
                - Arn
            Action: ["iam:PassRole"]
          - Effect: Allow
            Resource: "*
            Action: ["cloudfront:CreateInvalidation"]
      Roles: 
        - Ref: "DeploymentLambdaRole"

  UnpackZipIntoS3BucketFunctionLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: SharkSync.Deployment::SharkSync.Deployment.UnpackZipIntoS3BucketFunction::FunctionHandlerAsync
      Code:
        S3Bucket: io.sharksync.builds
        S3Key: 
          Fn::Join:
          - ''
          - - 'v0.0.0'
            - '/SharkSync.Deployment.zip'
      Role:
        Fn::GetAtt:
          - DeploymentLambdaRole
          - Arn
      Runtime: dotnetcore2.0
      MemorySize: 128
      Timeout: 60

  DeployLambdaEdgeFunctionLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: SharkSync.Deployment::SharkSync.Deployment.DeployLambdaEdgeFunction::FunctionHandlerAsync
      Code:
        S3Bucket: io.sharksync.builds
        S3Key: 
          Fn::Join:
          - ''
          - - 'v0.0.0'
            - '/SharkSync.Deployment.zip'
      Role:
        Fn::GetAtt:
          - DeploymentLambdaRole
          - Arn
      Runtime: dotnetcore2.0
      MemorySize: 128
      Timeout: 60
	  
  InvalidateCloudFrontFunctionLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: SharkSync.Deployment::SharkSync.Deployment.InvalidateCloudFrontFunction::FunctionHandlerAsync
      Code:
        S3Bucket: io.sharksync.builds
        S3Key: 
          Fn::Join:
          - ''
          - - 'v0.0.0'
            - '/SharkSync.Deployment.zip'
      Role:
        Fn::GetAtt:
          - DeploymentLambdaRole
          - Arn
      Runtime: dotnetcore2.0
      MemorySize: 128
      Timeout: 60

  UnpackZipIntoS3BucketFunction:
    Type: Custom::UnpackZipIntoS3BucketFunction
    DependsOn: UnpackZipIntoS3BucketFunctionLambda
    Properties:
      ServiceToken: !GetAtt UnpackZipIntoS3BucketFunctionLambda.Arn
      ZipS3Bucket: io.sharksync.builds
      ZipS3Key: 
        Fn::Join:
        - ''
        - - 'v0.0.0'
          - '/SharkSync.Web.Html.zip'
      OutputS3Bucket: !Ref S3BucketWeb
      OutputPrefix: ''

  LambdaEdgeOriginRequest:
    Type: Custom::DeployLambdaEdgeFunction
    DependsOn: DeployLambdaEdgeFunctionLambda
    Properties:
      ServiceToken: !GetAtt DeployLambdaEdgeFunctionLambda.Arn
      EmbeddedFileName: origin-request.js
      FunctionName: 
        Fn::Join:
        - ''
        - - !Ref 'AWS::StackName'
          - '-origin-request'
      RoleArn: 
        Fn::GetAtt:
          - LambdaEdgeRole
          - Arn

  InvalidateCloudFront:
    Type: Custom::InvalidateCloudFrontFunction
    DependsOn: 
      - InvalidateCloudFrontFunctionLambda
      - UnpackZipIntoS3BucketFunction
      - CloudFront
    Properties:
      ServiceToken: !GetAtt InvalidateCloudFrontFunctionLambda.Arn
      DistributionId: !Ref CloudFront
      CallerReference: 'v0.0.0'
      Paths: 
        - "/"
        - "/Console/*"