version: 0.2

phases:
  build:
    commands:
      - sudo apt-get update
      - sudo apt-get -y install apt-transport-https
      - wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
      - sudo dpkg -i packages-microsoft-prod.deb
      - sudo apt-get update
      - sudo apt-get -y install dotnet-sdk-2.1
      - cd SharkSync.IntegrationTests
      - dotnet test