version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get -y upgrade
      - apt-get install xvfb python python-pip build-essential apt-transport-https -y
      - pip install --upgrade pip
      - pip install selenium
      - cp xvfb.init /etc/init.d/xvfb
      - chmod +x /etc/init.d/xvfb
      - update-rc.d xvfb defaults
      - service xvfb start
      - export PATH="$PATH:`pwd`/webdrivers"
      - wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
      - sudo dpkg -i packages-microsoft-prod.deb
      - apt-get update
      - sudo apt-get -y install dotnet-sdk-2.1
  build:
    commands:
      - export DISPLAY=:5
      - cd SharkSync.IntegrationTests
      - dotnet test