version: 0.2

phases:
  build:
    commands:
      - dotnet restore --configuration release
      - dotnet build --configuration release
      - dotnet publish --configuration release
artifacts:
  files:
    - wwwroot/*