version: 0.2

phases:
  build:
    commands:
      - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      - apt-get install -y nodejs
      - dotnet restore
      - dotnet build --configuration release
      - dotnet publish --configuration release
      - aws s3 cp SharkTank.Web/bin/Release/netcoreapp2.0/publish/wwwroot s3://io.sharksync.web.html/ --recursive
artifacts:
  files:
    - '**/*'
  base-directory: 'SharkTank.Web/bin/Release/netcoreapp2.0/publish/wwwroot'