version: 0.2

phases:
  build:
    commands:
      - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      - apt-get install -y nodejs
      - dotnet restore
      - dotnet build --configuration release
      - dotnet publish --configuration release
      - serverless deploy --stage production
      - aws s3 cp SharkSync.Web/bin/Release/netcoreapp2.0/publish/wwwroot s3://io.sharksync.web/ --recursive