service: sharksync-web

plugins:
   - serverless-plugin-cloudfront-lambda-edge

package:
   exclude:
      - 'node_modules/**'

provider:
   name: aws
   runtime: nodejs6.10 # Because this runs on CloudFront (lambda@edge) it must be 6.10
   region: eu-west-1
   stage: dev
   profile: silvergames

functions:
   OriginRequestLambdaEdge:
      name: 'sharksync-web-origin-request'
      handler: 'Lambda@Edge/origin-request.js'
      memorySize: 128
      timeout: 1
      lambdaAtEdge:
         distribution: 'CloudFrontWebApp'
         eventType: 'origin-request'

resources:
   Resources:
      S3BucketWeb:
        Type: AWS::S3::Bucket
        DeletionPolicy: Retain
        Properties:
          BucketName: io.sharksync.web
      S3BucketPolicyBucketWebCloudfront:
        Type: AWS::S3::BucketPolicy
        Properties:
          Bucket:
            Ref: S3BucketWeb
          PolicyDocument:
            Statement:
            - Action:
              - s3:GetObject
              Effect: Allow
              Resource:
                Fn::Join:
                - ''
                - - 'arn:aws:s3:::'
                  - Ref: S3BucketWeb
                  - "/*"
              Principal:
                AWS:
                  - 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity E2L91VF2FR5I1N'
      CloudFrontWebApp:
        Type: AWS::CloudFront::Distribution
        Properties:
          DistributionConfig:
            Origins:
            - DomainName: io.sharksync.web.s3.amazonaws.com
              Id: s3
              S3OriginConfig:
                OriginAccessIdentity: origin-access-identity/cloudfront/E2L91VF2FR5I1N
            Enabled: 'true'
            Comment: io.sharksync.web
            DefaultRootObject: index.html
            DefaultCacheBehavior:
              AllowedMethods:
              - GET
              - HEAD
              TargetOriginId: s3
              ForwardedValues:
                QueryString: 'false'
                Cookies:
                  Forward: none
              SmoothStreaming: 'false'
              Compress: 'true'
              ViewerProtocolPolicy: redirect-to-https
            PriceClass: PriceClass_All
            HttpVersion: http2
